// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHint(arg1) {
  return window['go']['app']['App']['AddHint'](arg1);
}

export function AssignChallenge(arg1, arg2) {
  return window['go']['app']['App']['AssignChallenge'](arg1, arg2);
}

export function BanMember(arg1) {
  return window['go']['app']['App']['BanMember'](arg1);
}

export function CancelDownload(arg1) {
  return window['go']['app']['App']['CancelDownload'](arg1);
}

export function CancelUpload(arg1) {
  return window['go']['app']['App']['CancelUpload'](arg1);
}

export function ClearLogs() {
  return window['go']['app']['App']['ClearLogs']();
}

export function CreateChallenge(arg1) {
  return window['go']['app']['App']['CreateChallenge'](arg1);
}

export function DeleteChallenge(arg1) {
  return window['go']['app']['App']['DeleteChallenge'](arg1);
}

export function DeleteMessage(arg1) {
  return window['go']['app']['App']['DeleteMessage'](arg1);
}

export function DiscoverServers(arg1) {
  return window['go']['app']['App']['DiscoverServers'](arg1);
}

export function DownloadFile(arg1) {
  return window['go']['app']['App']['DownloadFile'](arg1);
}

export function ExportData(arg1, arg2) {
  return window['go']['app']['App']['ExportData'](arg1, arg2);
}

export function GetAppVersion() {
  return window['go']['app']['App']['GetAppVersion']();
}

export function GetChallenge(arg1) {
  return window['go']['app']['App']['GetChallenge'](arg1);
}

export function GetChallengeStats() {
  return window['go']['app']['App']['GetChallengeStats']();
}

export function GetChallengeSubmissions(arg1) {
  return window['go']['app']['App']['GetChallengeSubmissions'](arg1);
}

export function GetChallenges() {
  return window['go']['app']['App']['GetChallenges']();
}

export function GetClientStatus() {
  return window['go']['app']['App']['GetClientStatus']();
}

export function GetCurrentMode() {
  return window['go']['app']['App']['GetCurrentMode']();
}

export function GetDiscoveredServers() {
  return window['go']['app']['App']['GetDiscoveredServers']();
}

export function GetFile(arg1) {
  return window['go']['app']['App']['GetFile'](arg1);
}

export function GetFileProgress(arg1) {
  return window['go']['app']['App']['GetFileProgress'](arg1);
}

export function GetFileTransferStats() {
  return window['go']['app']['App']['GetFileTransferStats']();
}

export function GetFiles(arg1, arg2) {
  return window['go']['app']['App']['GetFiles'](arg1, arg2);
}

export function GetLeaderboard() {
  return window['go']['app']['App']['GetLeaderboard']();
}

export function GetLogs(arg1) {
  return window['go']['app']['App']['GetLogs'](arg1);
}

export function GetMember(arg1) {
  return window['go']['app']['App']['GetMember'](arg1);
}

export function GetMembers() {
  return window['go']['app']['App']['GetMembers']();
}

export function GetMessage(arg1) {
  return window['go']['app']['App']['GetMessage'](arg1);
}

export function GetMessages(arg1, arg2) {
  return window['go']['app']['App']['GetMessages'](arg1, arg2);
}

export function GetMyInfo() {
  return window['go']['app']['App']['GetMyInfo']();
}

export function GetNetworkInterfaces() {
  return window['go']['app']['App']['GetNetworkInterfaces']();
}

export function GetNetworkStats() {
  return window['go']['app']['App']['GetNetworkStats']();
}

export function GetRecentChannels() {
  return window['go']['app']['App']['GetRecentChannels']();
}

export function GetServerStatus() {
  return window['go']['app']['App']['GetServerStatus']();
}

export function GetUserProfile() {
  return window['go']['app']['App']['GetUserProfile']();
}

export function ImportData(arg1) {
  return window['go']['app']['App']['ImportData'](arg1);
}

export function IsRunning() {
  return window['go']['app']['App']['IsRunning']();
}

export function KickMember(arg1) {
  return window['go']['app']['App']['KickMember'](arg1);
}

export function MuteMember(arg1, arg2) {
  return window['go']['app']['App']['MuteMember'](arg1, arg2);
}

export function PinMessage(arg1) {
  return window['go']['app']['App']['PinMessage'](arg1);
}

export function ReactToMessage(arg1, arg2) {
  return window['go']['app']['App']['ReactToMessage'](arg1, arg2);
}

export function RemoveReaction(arg1, arg2) {
  return window['go']['app']['App']['RemoveReaction'](arg1, arg2);
}

export function SaveFileDialog(arg1, arg2) {
  return window['go']['app']['App']['SaveFileDialog'](arg1, arg2);
}

export function SearchMessages(arg1) {
  return window['go']['app']['App']['SearchMessages'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['app']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1, arg2) {
  return window['go']['app']['App']['SelectFile'](arg1, arg2);
}

export function SendCodeMessage(arg1) {
  return window['go']['app']['App']['SendCodeMessage'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['app']['App']['SendMessage'](arg1);
}

export function StartClientMode(arg1) {
  return window['go']['app']['App']['StartClientMode'](arg1);
}

export function StartServerMode(arg1) {
  return window['go']['app']['App']['StartServerMode'](arg1);
}

export function StopClientMode() {
  return window['go']['app']['App']['StopClientMode']();
}

export function StopServerMode() {
  return window['go']['app']['App']['StopServerMode']();
}

export function SubmitFlag(arg1) {
  return window['go']['app']['App']['SubmitFlag'](arg1);
}

export function TestConnection(arg1, arg2, arg3) {
  return window['go']['app']['App']['TestConnection'](arg1, arg2, arg3);
}

export function UnbanMember(arg1) {
  return window['go']['app']['App']['UnbanMember'](arg1);
}

export function UnlockHint(arg1, arg2) {
  return window['go']['app']['App']['UnlockHint'](arg1, arg2);
}

export function UnmuteMember(arg1) {
  return window['go']['app']['App']['UnmuteMember'](arg1);
}

export function UnpinMessage(arg1) {
  return window['go']['app']['App']['UnpinMessage'](arg1);
}

export function UpdateChallenge(arg1, arg2) {
  return window['go']['app']['App']['UpdateChallenge'](arg1, arg2);
}

export function UpdateChallengeProgress(arg1) {
  return window['go']['app']['App']['UpdateChallengeProgress'](arg1);
}

export function UpdateMemberRole(arg1, arg2) {
  return window['go']['app']['App']['UpdateMemberRole'](arg1, arg2);
}

export function UpdateMyProfile(arg1, arg2) {
  return window['go']['app']['App']['UpdateMyProfile'](arg1, arg2);
}

export function UpdateMyStatus(arg1) {
  return window['go']['app']['App']['UpdateMyStatus'](arg1);
}

export function UpdateUserProfile(arg1) {
  return window['go']['app']['App']['UpdateUserProfile'](arg1);
}

export function UploadFile(arg1) {
  return window['go']['app']['App']['UploadFile'](arg1);
}
