// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {models} from '../models';

export function AssignChallenge(arg1:string,arg2:Array<string>):Promise<app.Response>;

export function BanMember(arg1:app.BanMemberRequest):Promise<app.Response>;

export function CancelDownload(arg1:string):Promise<app.Response>;

export function CancelUpload(arg1:string):Promise<app.Response>;

export function ClearLogs():Promise<app.Response>;

export function CreateChallenge(arg1:app.CreateChallengeRequest):Promise<app.Response>;

export function DeleteChallenge(arg1:string):Promise<app.Response>;

export function DeleteFile(arg1:string):Promise<app.Response>;

export function DeleteMessage(arg1:string):Promise<app.Response>;

export function DiscoverServers(arg1:number):Promise<app.Response>;

export function DownloadFile(arg1:app.DownloadFileRequest):Promise<app.Response>;

export function ExportData(arg1:string,arg2:app.ExportOptions):Promise<app.Response>;

export function FetchHTTPSInfo(arg1:string,arg2:number,arg3:boolean,arg4:number):Promise<app.Response>;

export function GetAppVersion():Promise<string>;

export function GetChallenge(arg1:string):Promise<app.Response>;

export function GetChallengeProgress(arg1:string,arg2:string):Promise<app.Response>;

export function GetChallengeStats():Promise<app.Response>;

export function GetChallengeSubmissions(arg1:string):Promise<app.Response>;

export function GetChallenges():Promise<app.Response>;

export function GetClientStatus():Promise<app.Response>;

export function GetCurrentMode():Promise<string>;

export function GetDiscoveredServers():Promise<app.Response>;

export function GetFile(arg1:string):Promise<app.Response>;

export function GetFileContent(arg1:string):Promise<app.Response>;

export function GetFileProgress(arg1:string):Promise<app.Response>;

export function GetFileTransferStats():Promise<app.Response>;

export function GetFiles(arg1:number,arg2:number):Promise<app.Response>;

export function GetLeaderboard():Promise<app.Response>;

export function GetLogs(arg1:number):Promise<app.Response>;

export function GetMember(arg1:string):Promise<app.Response>;

export function GetMembers():Promise<app.Response>;

export function GetMessage(arg1:string):Promise<app.Response>;

export function GetMessages(arg1:number,arg2:number):Promise<app.Response>;

export function GetMessagesByChannel(arg1:string,arg2:number,arg3:number):Promise<app.Response>;

export function GetMyInfo():Promise<app.Response>;

export function GetNetworkInterfaces():Promise<app.Response>;

export function GetNetworkStats():Promise<app.Response>;

export function GetPinnedMessages():Promise<app.Response>;

export function GetRecentChannels():Promise<app.Response>;

export function GetServerStatus():Promise<app.Response>;

export function GetSubChannels():Promise<app.Response>;

export function GetTypingUsers():Promise<app.Response>;

export function GetUserProfile():Promise<app.Response>;

export function ImportData(arg1:string):Promise<app.Response>;

export function IsRunning():Promise<boolean>;

export function KickMember(arg1:app.KickMemberRequest):Promise<app.Response>;

export function MuteMember(arg1:string,arg2:number):Promise<app.Response>;

export function PinMessage(arg1:app.PinMessageRequest):Promise<app.Response>;

export function ReactToMessage(arg1:string,arg2:string):Promise<app.Response>;

export function RemoveReaction(arg1:string,arg2:string):Promise<app.Response>;

export function SaveFileDialog(arg1:string,arg2:string):Promise<app.Response>;

export function SearchMessages(arg1:app.SearchMessagesRequest):Promise<app.Response>;

export function SelectDirectory(arg1:string):Promise<app.Response>;

export function SelectFile(arg1:string,arg2:string):Promise<app.Response>;

export function SendCodeMessage(arg1:app.SendCodeRequest):Promise<app.Response>;

export function SendMessage(arg1:app.SendMessageRequest):Promise<app.Response>;

export function SetTypingStatus():Promise<app.Response>;

export function StartClientMode(arg1:app.ClientConfig):Promise<app.Response>;

export function StartServerMode(arg1:app.ServerConfig):Promise<app.Response>;

export function StopClientMode():Promise<app.Response>;

export function StopServerMode():Promise<app.Response>;

export function SubmitFlag(arg1:app.SubmitFlagRequest):Promise<app.Response>;

export function TestConnection(arg1:string,arg2:models.TransportMode,arg3:number):Promise<app.Response>;

export function UnbanMember(arg1:string):Promise<app.Response>;

export function UnmuteMember(arg1:string):Promise<app.Response>;

export function UnpinMessage(arg1:string):Promise<app.Response>;

export function UpdateChallenge(arg1:string,arg2:app.UpdateChallengeRequest):Promise<app.Response>;

export function UpdateChallengeProgress(arg1:app.UpdateProgressRequest):Promise<app.Response>;

export function UpdateMemberRole(arg1:string,arg2:models.Role):Promise<app.Response>;

export function UpdateMyProfile(arg1:string,arg2:string):Promise<app.Response>;

export function UpdateMyStatus(arg1:models.UserStatus):Promise<app.Response>;

export function UpdateUserProfile(arg1:app.UserProfile):Promise<app.Response>;

export function UploadFile(arg1:app.UploadFileRequest):Promise<app.Response>;
